server:
    port: 8090
    spring:
        resources:
        add-mappings:true
    compression:
        mime-types:text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    error:
        whitelabel:
            enabled:false
spring:
    datasource:
        url:jdbc:sqlserver://10.0.0.98:1433;databaseName=sssacontable
        username:contable19
        password:contable19
        driverClassName:com.microsoft.sqlserver.jdbc.SQLServerDriverjpa.show-sql=true
    jpa:
        hibernate:
            dialect:org.hibernate.dialect.SQLServer2005Dialect
            
